# Generated by Django 4.2.11 on 2024-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gravitymeasurement",
            name="sound",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
