# Generated by Django 4.2.11 on 2024-04-16 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WBB", "0003_shot"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Shot",
            new_name="Data",
        ),
    ]
