# Generated by Django 4.2.11 on 2024-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0004_rename_shot_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gravitymeasurement",
            name="center_of_gravity_x",
        ),
        migrations.RemoveField(
            model_name="gravitymeasurement",
            name="center_of_gravity_y",
        ),
        migrations.RemoveField(
            model_name="gravitymeasurement",
            name="sound",
        ),
        migrations.AddField(
            model_name="gravitymeasurement",
            name="shot",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
