# Generated by Django 4.2.11 on 2024-04-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0005_remove_gravitymeasurement_center_of_gravity_x_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Data",
        ),
    ]
