# Generated by Django 4.2.11 on 2024-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0006_delete_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gravitymeasurement",
            old_name="shot",
            new_name="gravity_center",
        ),
        migrations.AddField(
            model_name="gravitymeasurement",
            name="acceleration",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
