# Generated by Django 4.2.11 on 2024-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0008_rename_gravitymeasurement_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="session_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="data",
            name="shot_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
