# Generated by Django 4.2.11 on 2024-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0009_data_session_id_data_shot_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="shot_number",
        ),
        migrations.AddField(
            model_name="data",
            name="shot_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="data",
            name="session_id",
            field=models.IntegerField(default=1),
        ),
    ]
