# Generated by Django 4.2.11 on 2024-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WBB", "0012_alter_data_height_alter_data_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="acceleration",
        ),
        migrations.AddField(
            model_name="data",
            name="quaternion",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
